name: Update Project Status

on:
  pull_request:
    types:
      - closed

jobs:
  detect-branch:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:

      - name: Show Base Branch
        run: |
          echo "Base branch: ${{ github.base_ref }}"

      - name: Determine Status
        run: |
          if [[ "${{ github.base_ref }}" == "develop" ]]; then
            echo "Status: In Development"

          elif [[ "${{ github.base_ref }}" == "staging" ]]; then
            echo "Status: In Staging"

          elif [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "Status: Done"

          else
            echo "Branch not mapped"
          fi